/**
 * AutobahnCoordinate automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;
namespace DeutschlandAPI.SDK;
public class AutobahnCoordinate
{
    [JsonPropertyName("lat")]
    public string? Lat { get; set; }
    [JsonPropertyName("long")]
    public string? Long { get; set; }
}
