/**
 * AutobahnWarning automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;
namespace DeutschlandAPI.SDK;
public class AutobahnWarning
{
    [JsonPropertyName("id")]
    public string? Id { get; set; }
    [JsonPropertyName("blocked")]
    public bool? Blocked { get; set; }
    [JsonPropertyName("future")]
    public bool? Future { get; set; }
    [JsonPropertyName("title")]
    public string? Title { get; set; }
    [JsonPropertyName("subtitle")]
    public string? Subtitle { get; set; }
    [JsonPropertyName("description")]
    public List<string>? Description { get; set; }
    [JsonPropertyName("startDate")]
    public DateTime? StartDate { get; set; }
    [JsonPropertyName("coordinate")]
    public AutobahnCoordinate? Coordinate { get; set; }
    [JsonPropertyName("lineString")]
    public List<AutobahnCoordinate>? LineString { get; set; }
}
