/**
 * AutobahnChargingStationTag automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */


using System.Collections.Generic;
using System.Text.Json;
using System.Threading.Tasks;
using RestSharp;
using Sdkgen.Client;
using Sdkgen.Client.Exception;

namespace DeutschlandAPI.SDK;

public class AutobahnChargingStationTag : TagAbstract {
    public AutobahnChargingStationTag(RestClient httpClient, Parser parser): base(httpClient, parser)
    {
    }


    /**
     * Returns available charging stations for a specific autobahn
     */
    public async Task<AutobahnChargingStationCollection> GetAll(string autobahnId)
    {
        Dictionary<string, object> pathParams = new();
        pathParams.Add("autobahn_id", autobahnId);

        Dictionary<string, object> queryParams = new();

        List<string> queryStructNames = new();

        RestRequest request = new(this.Parser.Url("/autobahn/:autobahn_id/charging_station", pathParams), Method.Get);
        this.Parser.Query(request, queryParams, queryStructNames);

        RestResponse response = await this.HttpClient.ExecuteAsync(request);

        if (response.IsSuccessful)
        {
            return this.Parser.Parse<AutobahnChargingStationCollection>(response.Content);
        }

        throw (int) response.StatusCode switch
        {
            400 => new MessageException(this.Parser.Parse<Message>(response.Content)),
            404 => new MessageException(this.Parser.Parse<Message>(response.Content)),
            500 => new MessageException(this.Parser.Parse<Message>(response.Content)),
            _ => throw new UnknownStatusCodeException("The server returned an unknown status code"),
        };
    }


}
