/**
 * BudgetCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace DeutschlandAPI.SDK;

public class BudgetCollection
{
    [JsonPropertyName("entries")]
    public System.Collections.Generic.List<Budget>? Entries { get; set; }

}

