/**
 * BudgetTag automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */


using System.Collections.Generic;
using System.Text.Json;
using System.Threading.Tasks;
using RestSharp;
using Sdkgen.Client;
using Sdkgen.Client.Exception;

namespace DeutschlandAPI.SDK;

public class BudgetTag : TagAbstract {
    public BudgetTag(RestClient httpClient, Parser parser): base(httpClient, parser)
    {
    }

    public BudgetExpenseTag Expense()
    {
        return new BudgetExpenseTag(
            this.HttpClient,
            this.Parser
        );
    }

    public BudgetIncomeTag Income()
    {
        return new BudgetIncomeTag(
            this.HttpClient,
            this.Parser
        );
    }


}
