/**
 * Budget automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace DeutschlandAPI.SDK;

public class Budget
{
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    [JsonPropertyName("label")]
    public string? Label { get; set; }

    [JsonPropertyName("value")]
    public int? Value { get; set; }

    [JsonPropertyName("relativeToParentValue")]
    public int? RelativeToParentValue { get; set; }

    [JsonPropertyName("relativeValue")]
    public int? RelativeValue { get; set; }

}

