/**
 * BundestagMemberCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;
namespace DeutschlandAPI.SDK;
public class BundestagMemberCollection
{
    [JsonPropertyName("entries")]
    public List<BundestagMember>? Entries { get; set; }
}
