/**
 * BundestagMemberTag automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */


using System.Collections.Generic;
using System.Text.Json;
using System.Threading.Tasks;
using RestSharp;
using Sdkgen.Client;
using Sdkgen.Client.Exception;

namespace DeutschlandAPI.SDK;

public class BundestagMemberTag : TagAbstract {
    public BundestagMemberTag(RestClient httpClient, Parser parser): base(httpClient, parser)
    {
    }


    /**
     * Returns specific member of the Bundestag
     */
    public async Task<BundestagMember> Get(string memberId)
    {
        Dictionary<string, object> pathParams = new();
        pathParams.Add("member_id", memberId);

        Dictionary<string, object> queryParams = new();

        List<string> queryStructNames = new();

        RestRequest request = new(this.Parser.Url("/bundestag/member/:member_id", pathParams), Method.Get);
        this.Parser.Query(request, queryParams, queryStructNames);

        RestResponse response = await this.HttpClient.ExecuteAsync(request);

        if (response.IsSuccessful)
        {
            return this.Parser.Parse<BundestagMember>(response.Content);
        }

        throw (int) response.StatusCode switch
        {
            400 => new ResponseException(this.Parser.Parse<Response>(response.Content)),
            404 => new ResponseException(this.Parser.Parse<Response>(response.Content)),
            500 => new ResponseException(this.Parser.Parse<Response>(response.Content)),
            _ => throw new UnknownStatusCodeException("The server returned an unknown status code"),
        };
    }

    /**
     * Returns all current members of the Bundestag
     */
    public async Task<BundestagMemberCollection> GetAll()
    {
        Dictionary<string, object> pathParams = new();

        Dictionary<string, object> queryParams = new();

        List<string> queryStructNames = new();

        RestRequest request = new(this.Parser.Url("/bundestag/member", pathParams), Method.Get);
        this.Parser.Query(request, queryParams, queryStructNames);

        RestResponse response = await this.HttpClient.ExecuteAsync(request);

        if (response.IsSuccessful)
        {
            return this.Parser.Parse<BundestagMemberCollection>(response.Content);
        }

        throw (int) response.StatusCode switch
        {
            400 => new ResponseException(this.Parser.Parse<Response>(response.Content)),
            404 => new ResponseException(this.Parser.Parse<Response>(response.Content)),
            500 => new ResponseException(this.Parser.Parse<Response>(response.Content)),
            _ => throw new UnknownStatusCodeException("The server returned an unknown status code"),
        };
    }


}
