/**
 * BundesratTag automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */


using System.Collections.Generic;
using System.Text.Json;
using System.Threading.Tasks;
using RestSharp;
using Sdkgen.Client;
using Sdkgen.Client.Exception;

namespace DeutschlandAPI.SDK;

public class BundesratTag : TagAbstract {
    public BundesratTag(RestClient httpClient, Parser parser): base(httpClient, parser)
    {
    }

    public BundesratMemberTag Member()
    {
        return new BundesratMemberTag(
            this.HttpClient,
            this.Parser
        );
    }


}
