/**
 * BundesratMemberTag automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */


using System.Collections.Generic;
using System.Text.Json;
using System.Threading.Tasks;
using RestSharp;
using Sdkgen.Client;
using Sdkgen.Client.Exception;

namespace DeutschlandAPI.SDK;

public class BundesratMemberTag : TagAbstract {
    public BundesratMemberTag(RestClient httpClient, Parser parser): base(httpClient, parser)
    {
    }


    /**
     * Returns all current members of the Bundesrat
     */
    public async Task<BundesratMemberCollection> GetAll()
    {
        Dictionary<string, object> pathParams = new();

        Dictionary<string, object> queryParams = new();

        List<string> queryStructNames = new();

        RestRequest request = new(this.Parser.Url("/bundesrat/member", pathParams), Method.Get);
        this.Parser.Query(request, queryParams, queryStructNames);


        RestResponse response = await this.HttpClient.ExecuteAsync(request);

        if (response.IsSuccessful)
        {
            var data = this.Parser.Parse<BundesratMemberCollection>(response.Content);

            return data;
        }

        var statusCode = (int) response.StatusCode;
        if (statusCode == 400)
        {
            var data = this.Parser.Parse<Response>(response.Content);

            throw new ResponseException(data);
        }

        if (statusCode == 404)
        {
            var data = this.Parser.Parse<Response>(response.Content);

            throw new ResponseException(data);
        }

        if (statusCode == 500)
        {
            var data = this.Parser.Parse<Response>(response.Content);

            throw new ResponseException(data);
        }

        throw new UnknownStatusCodeException("The server returned an unknown status code: " + statusCode);
    }


}
