/**
 * BundestagConstituency automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;
namespace DeutschlandAPI.SDK;
public class BundestagConstituency
{
    [JsonPropertyName("number")]
    public string? Number { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
}
