/**
 * City automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;
namespace DeutschlandAPI.SDK;
public class City
{
    [JsonPropertyName("id")]
    public int? Id { get; set; }
    [JsonPropertyName("state")]
    public string? State { get; set; }
    [JsonPropertyName("rb")]
    public string? Rb { get; set; }
    [JsonPropertyName("district")]
    public string? District { get; set; }
    [JsonPropertyName("verb")]
    public string? Verb { get; set; }
    [JsonPropertyName("gem")]
    public string? Gem { get; set; }
    [JsonPropertyName("zipCode")]
    public string? ZipCode { get; set; }
    [JsonPropertyName("area")]
    public int? Area { get; set; }
}
