/**
 * Client automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */


using System.Collections.Generic;
using System.Text.Json;
using System.Threading.Tasks;
using RestSharp;
using Sdkgen.Client;
using Sdkgen.Client.Credentials;
using Sdkgen.Client.Exception;

namespace DeutschlandAPI.SDK;

public class Client : ClientAbstract
{
    public Client(string baseUrl, ICredentials credentials) : base(baseUrl, credentials)
    {
    }

    public HospitalTag Hospital()
    {
        return new HospitalTag(
            this.HttpClient,
            this.Parser
        );
    }

    public WarningTag Warning()
    {
        return new WarningTag(
            this.HttpClient,
            this.Parser
        );
    }

    public CityTag City()
    {
        return new CityTag(
            this.HttpClient,
            this.Parser
        );
    }

    public DistrictTag District()
    {
        return new DistrictTag(
            this.HttpClient,
            this.Parser
        );
    }

    public StateTag State()
    {
        return new StateTag(
            this.HttpClient,
            this.Parser
        );
    }

    public BundestagTag Bundestag()
    {
        return new BundestagTag(
            this.HttpClient,
            this.Parser
        );
    }

    public BundesratTag Bundesrat()
    {
        return new BundesratTag(
            this.HttpClient,
            this.Parser
        );
    }

    public AutobahnTag Autobahn()
    {
        return new AutobahnTag(
            this.HttpClient,
            this.Parser
        );
    }

    public AuthorizationTag Authorization()
    {
        return new AuthorizationTag(
            this.HttpClient,
            this.Parser
        );
    }

    public MetaTag Meta()
    {
        return new MetaTag(
            this.HttpClient,
            this.Parser
        );
    }



    public static Client Build(string clientId, string clientSecret, ITokenStore tokenStore, List<string> scopes)
    {
        return new Client("https://api.deutschland-api.dev/", new OAuth2(clientId, clientSecret, "https://api.deutschland-api.dev/authorization/token", "", tokenStore, scopes));
    }

    public static Client BuildAnonymous()
    {
        return new Client("https://api.deutschland-api.dev/", new Anonymous());
    }
}
