/**
 * District automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;
namespace DeutschlandAPI.SDK;
public class District
{
    [JsonPropertyName("id")]
    public string? Id { get; set; }
    [JsonPropertyName("state")]
    public string? State { get; set; }
    [JsonPropertyName("type")]
    public string? Type { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("nuts3")]
    public string? Nuts { get; set; }
    [JsonPropertyName("area")]
    public int? Area { get; set; }
}
