/**
 * HospitalTag automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */


using System.Collections.Generic;
using System.Text.Json;
using System.Threading.Tasks;
using RestSharp;
using Sdkgen.Client;
using Sdkgen.Client.Exception;

namespace DeutschlandAPI.SDK;

public class HospitalTag : TagAbstract {
    public HospitalTag(RestClient httpClient, Parser parser): base(httpClient, parser)
    {
    }


    /**
     * Returns all available hospitals
     */
    public async Task<HospitalCollection> GetAll(int startIndex, string search)
    {
        Dictionary<string, object> pathParams = new();

        Dictionary<string, object> queryParams = new();
        queryParams.Add("startIndex", startIndex);
        queryParams.Add("search", search);

        List<string> queryStructNames = new();

        RestRequest request = new(this.Parser.Url("/hospital", pathParams), Method.Get);
        this.Parser.Query(request, queryParams, queryStructNames);

        RestResponse response = await this.HttpClient.ExecuteAsync(request);

        if (response.IsSuccessful)
        {
            return this.Parser.Parse<HospitalCollection>(response.Content);
        }

        throw (int) response.StatusCode switch
        {
            400 => new ResponseException(this.Parser.Parse<Response>(response.Content)),
            404 => new ResponseException(this.Parser.Parse<Response>(response.Content)),
            500 => new ResponseException(this.Parser.Parse<Response>(response.Content)),
            _ => throw new UnknownStatusCodeException("The server returned an unknown status code"),
        };
    }


}
