/**
 * Job automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;
namespace DeutschlandAPI.SDK;
public class Job
{
    [JsonPropertyName("job")]
    public string? Job { get; set; }
    [JsonPropertyName("title")]
    public string? Title { get; set; }
    [JsonPropertyName("number")]
    public string? Number { get; set; }
    [JsonPropertyName("location")]
    public JobLocation? Location { get; set; }
    [JsonPropertyName("employer")]
    public string? Employer { get; set; }
    [JsonPropertyName("publishDate")]
    public DateTime? PublishDate { get; set; }
    [JsonPropertyName("entranceDate")]
    public DateTime? EntranceDate { get; set; }
}
