/**
 * JobLocation automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;
namespace DeutschlandAPI.SDK;
public class JobLocation
{
    [JsonPropertyName("zip")]
    public string? Zip { get; set; }
    [JsonPropertyName("place")]
    public string? Place { get; set; }
    [JsonPropertyName("state")]
    public string? State { get; set; }
    [JsonPropertyName("country")]
    public string? Country { get; set; }
    [JsonPropertyName("coordinate")]
    public JobCoordinate? Coordinate { get; set; }
}
