/**
 * SystemAboutLink automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;
namespace DeutschlandAPI.SDK;
public class SystemAboutLink
{
    [JsonPropertyName("rel")]
    public string? Rel { get; set; }
    [JsonPropertyName("href")]
    public string? Href { get; set; }
}
