/**
 * WarningCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;
namespace DeutschlandAPI.SDK;
public class WarningCollection
{
    [JsonPropertyName("entries")]
    public List<Warning>? Entries { get; set; }
}
